spring:
  config:
    import:
      - profiles/application-app.yml
      - profiles/application-datasource.yml
      - profiles/application-oauth2.yml
      - profiles/application-email.yml
  jackson:
    property-naming-strategy: SNAKE_CASE
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB
mybatis:
  type-handlers-package: "com.oauth2.sample.web.mybatis.handler"
logging:
  level:
    com.oauth2.sample.web.mybatis: debug
