spring:
  config:
    import:
      - profiles/application-app.yml
      - profiles/application-datasource.yml
      - profiles/application-oauth2.yml
  jackson:
    property-naming-strategy: SNAKE_CASE
mybatis:
  type-handlers-package: "com.oauth2.sample.web.mybatis.handler"
logging:
  level:
    com.oauth2.sample.web.mybatis: debug
