spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: guswnsemailserver@gmail.com
    password: iznvqnwqigcdhadq
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000