app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC926D96C90030DD58429D2751AC1BDBBC # JWT를 암호화 하기 위한 암호화 키
    ACCESS_TOKEN_EXPIRE_LENGTH: 60000  # token 만료 기간 (24h * 60min * 60s * 1000ms) 3600000
    REFRESH_TOKEN_EXPIRE_LENGTH: 604800000
    refresh-cookie-key: "refresh"
  oauth2:
    authorizedRedirectUris:
    - http://localhost:3000/oauth2/redirect
    - http://localhost:5500

